// Builds the copy-paste files from etch/src/component.mjs and etch/contact-form.js:
//   etch/contact-form.html      plain HTML (props filled with their defaults)
//   etch/contact-form.css       all class styles + keyframes
//   etch/create-component.js    script for the Etch Connector that creates the component in Etch Studio
//   etch/contact-form.etch.json Etch clipboard JSON – copy & paste into the Etch Studio builder
// Run: node etch/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { KEY, DESCRIPTION, PROPS, TREE, KEYFRAMES, STYLES } from './src/component.mjs';

const dir = new URL('.', import.meta.url);
const read = (file) => readFileSync(new URL(file, dir), 'utf8');
const write = (file, content) => writeFileSync(new URL(file, dir), content);

const defaults = Object.fromEntries(PROPS.map(([, key, value]) => [key, value]));
const fill = (value) => value.replace(/\{props\.(\w+)\}/g, (_, key) => defaults[key] ?? '');
const esc = (value) => value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const VOID = new Set(['input', 'br', 'hr', 'img']);
const INLINE = new Set(['label', 'span', 'a', 'button', 'p', 'textarea']);

// --- HTML -------------------------------------------------------------------
const render = (node, depth = 0) => {
  if (node.text !== undefined) return esc(fill(node.text));
  const pad = '  '.repeat(depth);
  const attrs = Object.entries({ class: node.cls, ...node.attributes })
    .map(([name, value]) => (value === '' ? ` ${name}` : ` ${name}="${esc(fill(value))}"`)).join('');
  if (VOID.has(node.tag)) return `${pad}<${node.tag}${attrs}>`;
  const inline = INLINE.has(node.tag) || node.children.every((child) => child.text !== undefined);
  if (inline) {
    const inner = node.children.map((child) => (child.text !== undefined ? render(child) : render(child).trim())).join('');
    return `${pad}<${node.tag}${attrs}>${inner}</${node.tag}>`;
  }
  return `${pad}<${node.tag}${attrs}>\n${node.children.map((child) => render(child, depth + 1)).join('\n')}\n${pad}</${node.tag}>`;
};

write('contact-form.html', `<!-- Contact form – plain HTML version of the Etch component „${KEY}“.
     Styles: contact-form.css · Script: contact-form.js (add it once to the page, or as block script on the form).
     Set the form action to your worker URL. Generated by etch/build.mjs – edit etch/src/component.mjs instead. -->
${render(TREE)}
`);

// --- CSS --------------------------------------------------------------------
const indent = (css) => css.split('\n').map((line) => (line ? `  ${line}` : line)).join('\n');
write('contact-form.css', `/* Contact form – styles for the Etch component „${KEY}“ (BEM block .contact-form).
   Theme it via the --contact-form-* custom properties on .contact-form.
   Generated by etch/build.mjs – edit etch/src/component.mjs instead. */

${KEYFRAMES}

${Object.entries(STYLES).map(([selector, css]) => `${selector} {\n${indent(css || '/* hook – no styles by default */')}\n}`).join('\n\n')}
`);

// --- Etch Connector script --------------------------------------------------
const data = { key: KEY, description: DESCRIPTION, props: PROPS, tree: TREE, keyframes: KEYFRAMES, styles: STYLES, script: read('contact-form.js') };
write('create-component.js', `// Creates the Etch component „${KEY}“ in Etch Studio via the Etch Connector (https://www.npmjs.com/package/@digital-gravy/etch-connector).
// What it does:
//   1. appends @keyframes contact-form-spin to your stylesheet „Main“ (or the first stylesheet) – stylesheets persist immediately
//   2. creates the class styles (.contact-form, .contact-form__*) – existing selectors are left untouched
//   3. creates the component with props and the block script (contact-form.js) on the form
//   4. saves the builder (etch.saveAsync) – class styles are buffered and would be lost on reload otherwise.
//      Note: this also saves any other unsaved changes on the page that is open.
// Run (Etch Studio open in the browser, connector running – see README):
//   npx -y @digital-gravy/etch-connector eval -t <tab> -f etch/create-component.js --timeout 60000
// Generated by etch/build.mjs – edit etch/src/component.mjs instead.
const DATA = ${JSON.stringify(data, null, 2)};

if (etch.blocks.isInComponentEditMode()) throw new Error('Leave the component edit mode first');
if (etch.components.list().some((c) => c.key === DATA.key)) throw new Error(\`Component \${DATA.key} already exists – rename or delete it first\`);

// 1. Keyframes
const sheets = await etch.stylesheets.list();
const sheet = sheets.find((s) => s.name === 'Main') || sheets[0];
if (!sheet) throw new Error('No stylesheet found – create one in Etch Studio first');
if (!(sheet.css || '').includes('@keyframes contact-form-spin')) await etch.stylesheets.appendAsync(sheet.id, DATA.keyframes);

// 2. Class styles
const ids = Object.fromEntries(etch.styles.list().map((s) => [s.selector, s.id]));
const kept = [];
for (const [selector, css] of Object.entries(DATA.styles)) {
  if (ids[selector]) kept.push(selector);
  else ids[selector] = etch.styles.create(selector, css);
}

// 3. Component
const toBlock = (node) => node.text !== undefined
  ? { type: 'etch/text', version: 1, context: {}, text: node.text, children: [] }
  : {
      type: 'etch/element', version: 1, context: { name: node.cls }, tag: node.tag,
      attributes: { ...node.attributes, class: node.cls },
      styles: [ids['.' + node.cls]].filter(Boolean),
      children: node.children.map(toBlock)
    };
const root = toBlock(DATA.tree);
root.script = { code: DATA.script };

const id = await etch.components.createAsync(DATA.key);
await etch.components.updateAsync(id, {
  key: DATA.key,
  description: DATA.description,
  properties: DATA.props.map(([name, key, value]) => ({ name, key, type: { primitive: 'string' }, default: value })),
  blocks: [root]
});

// 4. Save (class styles are buffered)
await etch.saveAsync();

return { componentId: id, stylesheet: sheet.name, existingStylesKept: kept, next: 'Reload the Etch tab, insert the component and set the „Endpoint“ prop.' };
`);

// --- Etch clipboard JSON (copy the file content, click into the Etch Studio canvas, paste) --------
// Format = what Etch Studio's own copy produces (version 2.1): one etch/component block plus the
// component definition and its class styles. Stylesheets aren't part of it → keyframes go in by hand.
const hashId = (text) => {
  let h = 2166136261;
  for (const ch of text) h = Math.imul(h ^ ch.charCodeAt(0), 16777619) >>> 0;
  return h.toString(36).padStart(7, '0').slice(-7);
};
const COMPONENT_ID = 9001; // placeholder – Etch assigns its own on paste
const toGutenberg = (node) => {
  if (node.text !== undefined) {
    return { blockName: 'etch/text', attrs: { metadata: { name: 'Text' }, content: node.text }, innerBlocks: [], innerHTML: '', innerContent: [] };
  }
  const children = node.children.map(toGutenberg);
  const attrs = { metadata: { name: node.cls }, tag: node.tag, attributes: { ...node.attributes, class: node.cls }, styles: [hashId('.' + node.cls)] };
  return {
    blockName: 'etch/element',
    attrs,
    innerBlocks: children,
    innerHTML: '\n'.repeat(Math.max(2, children.length * 2)),
    innerContent: children.length ? ['\n', ...children.flatMap((_, i) => (i ? ['\n\n', null] : [null])), '\n'] : ['\n', '\n']
  };
};
const formBlock = toGutenberg(TREE);
formBlock.attrs = { ...formBlock.attrs, script: { code: Buffer.from(read('contact-form.js'), 'utf8').toString('base64'), id: hashId('script') } };

write('contact-form.etch.json', JSON.stringify({
  type: 'block',
  gutenbergBlock: {
    blockName: 'etch/component',
    attrs: { metadata: { name: KEY }, ref: COMPONENT_ID, attributes: {} },
    innerBlocks: [],
    innerHTML: '\n\n',
    innerContent: ['\n', '\n']
  },
  timestamp: '2026-10-05T00:00:00.000Z',
  styles: Object.fromEntries(Object.entries(STYLES).map(([selector, css]) => [hashId(selector), { selector, collection: 'default', css, readonly: false }])),
  components: {
    [COMPONENT_ID]: {
      id: COMPONENT_ID,
      name: KEY,
      key: KEY,
      description: DESCRIPTION,
      properties: PROPS.map(([name, key, value]) => ({ default: value, key, name, type: { primitive: 'string' } })),
      blocks: [formBlock]
    }
  },
  customMediaDefinitions: {},
  version: 2.1
}, null, 2) + '\n');

// --- Demo page (open demo/index.html in a browser to preview the form) -------
writeFileSync(new URL('../demo/index.html', dir), `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Contact form demo</title>
  <link rel="stylesheet" href="../etch/contact-form.css">
  <style>body { max-inline-size: 44rem; margin: 3rem auto; padding-inline: 1rem; font-family: system-ui, sans-serif; }</style>
</head>
<body>
  <h1>Contact form demo</h1>
${render(TREE, 1)}
  <script src="../etch/contact-form.js"></script>
</body>
</html>
`);

console.log('Built contact-form.html, contact-form.css, contact-form.etch.json, create-component.js, demo/index.html');
